name: laps
channels:
  - conda-forge
  - pytorch
  - anaconda
dependencies:
  - python=3.7.7
  - appdirs
  - appnope
  - attrs
  - backcall
  - black
  - bleach
  - cairocffi
  - certifi
  - cffi
  - chardet
  - click
  - colorama
  - cycler
  - decorator
  - defusedxml
  - dill
  - docopt
  - entrypoints
  - frozendict
  - graphviz
  - idna
  - imageio
  - importlib-metadata
  - iniconfig
  - jedi
  - Jinja2
  - joblib
  - jsonschema
  - jupyterlab
  - kiwisolver
  - MarkupSafe
  - matplotlib
  - mistune
  - multiprocess
  - nltk
  - notebook
  - num2words
  - numpy
  - packaging
  - pandas
  - pandocfilters
  - parso
  - pathos
  - pathspec
  - pexpect
  - pickleshare
  - Pillow
  - pip
  - pluggy
  - pox
  - ppft
  - pre-commit
  - prompt_toolkit
  - protobuf
  - psutil
  - ptyprocess
  - py
  - pycparser
  - Pygments
  - pyparsing
  - pypng
  - pyrsistent
  - pytest
  - python-dateutil
  - pytorch
  - pytz
  - PyYAML
  - pyzmq
  - qtconsole
  - regex
  - requests
  - scikit-learn
  - scipy
  - seaborn
  - Send2Trash
  - sexpdata
  - six
  - terminado
  - testpath
  - toml
  - tomli
  - torchvision
  - tornado
  - tqdm
  - traitlets
  - typed-ast
  - typing-extensions
  - urllib3
  - wcwidth
  - webencodings
  - zipp
  - pip:
    - mypy-extensions
    - phx-class-registry
    - pregex
    - pytorch-nlp